### ISSUE TITLE
Update webpack to version 5

### ISSUE THREAD

**Issue by rajzik** [beemojs/beemo#100]
@milesj would it be possible to update webpack driver to webpack@5?

**Comment by milesj** [comment]
I will land this as part of v2.

**Comment by rajzik** [comment]
@milesj is there any estimation when it should be?

**Comment by milesj** [comment]
Webpack change is currently in this PR: https://github.com/beemojs/beemo/pull/101

I'm hoping to have an alpha release of v2 by end of week.

**Comment by milesj** [comment]
Will land in v2.
