### ISSUE TITLE
CLI Args need typings in v2

### ISSUE THREAD

**Issue by domoritz** [beemojs/beemo#112]
It used to not be necessary to explicitly mention the cli args. Is this intended?

<img width="757" alt="Screen Shot 2021-02-23 at 12 31 41" src="https://user-images.githubusercontent.com/589034/108837804-a6899000-7587-11eb-96f1-da0da7a9ac0b.png">

**Comment by milesj** [comment]
Yeah, this is completely different now in v2. You would most likely need to use `context.getRiskyOption('react')` as `--react` is technically an unknown option (assuming).

**Comment by domoritz** [comment]
Makes sense. Done in https://github.com/vega/vega-lite-dev-config/commit/0d581887677338ded8e0c8902138b4f640d4229f

**Comment by milesj** [comment]
I'll see if we can type this somehow, but it'll be tricky. I'll also add it to the migration docs.
