### ISSUE TITLE
Eslint env type missing

### ISSUE THREAD

**Issue by domoritz** [beemojs/beemo#113]
<img width="959" alt="Screen Shot 2021-02-23 at 12 33 37" src="https://user-images.githubusercontent.com/589034/108838028-f1a3a300-7587-11eb-8082-2bbe51b8ed66.png">

**Comment by milesj** [comment]
I noticed this as well. Seems like the types from `eslint` don't provide everything. My mistake.

**Comment by milesj** [comment]
This should be fixed now.
