### ISSUE TITLE
Add custom options

### ISSUE THREAD

**Issue by domoritz** [beemojs/beemo#115]
I want to preconfigure a driver but allow consumers to easily customize the driver. For example, I want them to be able to pass whether they want a config for node or the browser. More specifically, I want to tell only the babel driver that I am running in a browser since I may only use babel for jest but my project should also work in the browser. 

Is my only way to do that through command line arguments to `beemo create-config`? How would I pass for example an object?

**Comment by milesj** [comment]
Hrrmm, this can maybe be done with custom settings? https://github.com/beemojs/beemo/blob/master/docs/tips.md#custom-settings

Then in your config module Babel config, you could check the settings with `process.beemo.tool.config.settings`? I do something similar with my personal config. https://github.com/milesj/build-tool-config/blob/master/packages/config/src/configs/babel.ts#L12

**Comment by domoritz** [comment]
I see. So there is no way to define driver-specific custom settings?

**Comment by milesj** [comment]
@domoritz There is not, but you could maybe group it within settings?

```js
{
  settings: {
    babel: {
      esm: true
    }
  }
}
```

**Comment by domoritz** [comment]
Great suggestion. I will do that.
