### ISSUE TITLE
Provide ConfigFile type for consumers

### ISSUE THREAD

**Issue by domoritz** [beemojs/beemo#116]
I would like to type my config files but the default `ConfigFile` type expects properties that are not needed. 

```ts
import {ConfigFile} from '@beemo/core';

const config: ConfigFile = {
  module: '@local',
  drivers: {
    prettier: true,
    typescript: {
      foo: 'hello',
    },
  },
};

export default config;
```

**Comment by milesj** [comment]
Added a `BeemoConfig` type.

**Comment by domoritz** [comment]
Why is `BeemoConfig` not just `Partial<ConfigFile>`?

**Comment by milesj** [comment]
@domoritz Because it needs to be deeply partial, but a `DeepPartial` type was causing some issues with the `drivers`/`scripts` fields. I agree it's not ideal, but also not critical at the moment.
