### ISSUE TITLE
Unclear where configuration module goes

### ISSUE THREAD

**Issue by domoritz** [beemojs/beemo#118]
Looking at https://milesj.gitbook.io/beemo/tool/events, I don't understand whetehr I make a file `src/index.ts` and that's it or whether I also need to run ts to create `lib/index.js`.

**Comment by milesj** [comment]
@domoritz It uses Node's require resolution, which is based on the package `main` field. So the file can technically be anywhere, but it needs to be JavaScript.

**Comment by domoritz** [comment]
I see. I think the docs should clarify this since drivers can be pure typescript even in the published package (right?).

**Comment by milesj** [comment]
@domoritz Correct. The only way I can think of doing this is not using `main`.

**Comment by milesj** [comment]
Added file lookups and updated docs.
