### ISSUE TITLE
create-config --silent is not a recognized argument

### ISSUE THREAD

**Issue by niieani** [beemojs/beemo#147]
Sorry for the influx of issues, just trying to setup my project and stumbling upon some issues.

The docs mention a `--silent` argument for `create-config`: https://github.com/beemojs/beemo/blob/ab4d6c3eb09a0f3f1d2833b585e6c018685a9a86/website/docs/advanced.md#editor-integration
but it looks like no such argument was implemented (can't find references in code).

There are a few other minor issues with the docs, e.g. [the example](https://beemo.dev/docs/provider#scripts) for creating Scripts shows incorrect return value for the `parse` function. Fortunately the types are correct, so it was easy to figure out.

**Comment by milesj** [comment]
@niieani `--silent` was removed in v2, so the docs are just out of date.
