### ISSUE TITLE
Consider relaxing requirement for configs to not be functions

### ISSUE THREAD

**Issue by niieani** [beemojs/beemo#148]
The current behavior is that beemo throws when the config is a function.

https://github.com/beemojs/beemo/blob/148035874cd7572aa7c04105b274d452b2e86655/packages/core/src/routines/CreateConfigRoutine.ts#L289-L295

However this is quite fine when using the REFERENCE strategy, because no actual merging is happening, and the config is just being re-exported.

My use case is webpack, which accepts a function as config that can be parametrized with command line args, e.g.:

```js
/** @type {(env: Record<string, string | boolean>) => import('webpack').Configuration} */
module.exports = ({
  codeTarget = 'es2020',
}) => ({
  target: codeTarget,
})

```

My workaround right now is to monkey-patch beemo, but I'd much prefer an official way:

```ts
import {requireModule} from '@boost/module'
import {CreateConfigRoutine} from '@beemo/core/lib/routines/CreateConfigRoutine'

// monkey patch to allow functions to be used as configs
CreateConfigRoutine.prototype.loadConfigAtPath = function loadConfigAtPath(
  filePath: Path,
): ConfigObject {
  const config = requireModule<ConfigObject>(filePath).default
  return config
}
```

**Comment by milesj** [comment]
@niieani Functions cannot be serialized, so how do you expect this to merge & create the config? Maybe the copy strategy would work here?

**Comment by niieani** [comment]
webpack uses the reference strategy, so functions are totally fine as no merging occurs. Copy strategy would work too.

**Comment by milesj** [comment]
Fixed in the next version.
