### ISSUE TITLE
How to change `strategy` in provider

### ISSUE THREAD

**Issue by rajzik** [beemojs/beemo#152]
Currently I am migrating to beemo v2 and I am facing issue with webpack config. I would like to change strategy from `STRATEGY_REFERENCE` to `STRATEGY_CREATE`.

I didn't find any guidance on how to do it or if it is even possible.

I want to change strategy so we can update configs the same way as eslint or typescript, but this isn't possible when using reference.

**Comment by milesj** [comment]
@rajzik There's no way to change it on the provider, only on the consumer.

```js
module.exports = {
    module: '<config-module>',
    drivers: [
        [
            'webpack',
            {
                configStrategy: 'create',
            },
        ],
    ],
};
```
