### ISSUE TITLE
Driver webpack incorrect behavior

### ISSUE THREAD

**Issue by rajzik** [beemojs/beemo#153]
Due to resolution of the beemo. Typescript file is selected when running create-config for webpack. instead of js file.
Can this be fixed as webpack doesn't have native support for webpack configs?

**Comment by milesj** [comment]
@rajzik TS always takes precedence. I'd suggest not publishing the TS files if you only want JS to be used.

**Comment by rajzik** [comment]
@milesj I am using packemon and it generates `files` field in `package.json` and I didn't find how to disable it.

**Comment by milesj** [comment]
@rajzik Ah yeah, you can't.

I think it makes sense to only use the JS files when the strategy is copy.

**Comment by rajzik** [comment]
@milesj I have found workaround that is working but it's bad. 

you can add prepack script that removes src from files. 

Also, I found another issue with webpack, webpack config still doesn't have access to the `beemo.tool` or `lumos.tool` in my case. 

Is there any working example how to setup webpack config?

**Comment by milesj** [comment]
@rajzik Are you talking about `process.beemo.tool`? Because the process stuff is only available when a config is generated, not copied/referenced.

**Comment by rajzik** [comment]
@milesj I see, in previous version it was possible to get setting in multiple ways. I will implement it like shown and if it is intended to have only settings for generated config then I can do it on my own. thanks.

**Comment by milesj** [comment]
@rajzik It's only available for generated config, not because I haven't built it for others, but because it's impossible to support or others.

When their config is loaded, it's loaded by their own tool (webpack, jest, etc), which is a _separate process_, so I'm unable to inject beemo into it.

That being said, I can fix the copy/ref issue this week.

**Comment by rajzik** [comment]
@milesj I was trying to run lumos webpack serve and there was missing beemo tool after it got to webpack-cli. 

And it would be great if you fix the issue ref config. Thank you.

**Comment by milesj** [comment]
@rajzik Released a new patch that will only use js files for copy/ref. Let me know if that works.

**Comment by rajzik** [comment]
Issue is resolved. Closing. Thanks @milesj
