### ISSUE TITLE
Support for specific monorepo structure

### ISSUE THREAD

**Issue by jakubmazanec** [beemojs/beemo#156]
I have a question about Beemo's monorepo support. Imagine following structure (I included only files and folders needed for my explanation):

```
monorepo/
├── .config/
├── packages/
│   ├── nextjs-app/
│   │   ├── .config/
│   │   ├── .eslintrc.js
│   │   └── package.json
│   └── some-package/
└── .eslintrc.js
```

The root ESLint config contains all needed settings (plugins, rules, etc.) except settings related to [Next.js ESLint plugin](https://www.npmjs.com/package/@next/eslint-plugin-next). This plugins make certain assumptions (e.g. `pages` folder being present), and therefore I don't want to use it in the packages that aren't actually a Next.js app (e.g. `some-package`) - hence the file `monorepo/packages/nextjs-app/.eslintrc.js` that adds the settings that are not in the root ESLint config.

So, my question is - when I run `lint` script defined in `monorepo/packages/nextjs-app/package.json` (something like `beemo eslint src/**/*.js`), is Beemo able to create such ESLint config files (based on Beemo config files in both `monorepo/.config` and `monorepo/packages/nextjs-app/.config` folders) and run the ESLint for the `nextjs-app` package? Thanks in advance.

**Comment by milesj** [comment]
@jakubmazanec Beemo was designed to only be ran from the root of the repo, so I'm leaning towards no, this wouldn't be possible.

However, if you did run beemo from the root, ESLint would "just work" and inherit the nested `.eslintrc.js` files because that's just how ESLint works. No special config needed.

**Comment by jakubmazanec** [comment]
Ok, thanks for the info.
