### ISSUE TITLE
[Question] swc vs babel

### ISSUE THREAD

**Issue by bclark-p44** [beemojs/beemo#157]
Hey @milesj, 

What are your current thoughts around SWC support within Beemo? I use Packemon for my package compiler and I know that it experimental SWC support. I would love to use SWC for jest, would it be as simple as updating the jest config within my packages to use swc-jest?

**Comment by milesj** [comment]
@bclark-p44 Yeah, in you're jest config, you probably just need:

```
  transform: {
    '^.+\\.(t|j)sx?$': '@swc/jest',
  },
```

**Comment by bclark-p44** [comment]
Cool, that's what I figured! Thanks
