### ISSUE TITLE
Use a real dependency graph for priority sort

### ISSUE THREAD

**Issue by milesj** [beemojs/beemo#32]
At the moment, if 2 dependencies have the same number of dependents, but one needs to run before the other, it may fail based on how packages were loaded from the file system. For example

```
foo
bar - depends on foo
baz - depends on bar
```

Ideally our chain would be `foo -> bar -> baz`, but since `foo` and `bar` both have 1 dependent, `foo` may come after `bar`, as such `bar -> foo -> baz`, which breaks for projects that require explicit order (like TS).

**Comment by milesj** [comment]
Possible packages: 

- https://www.npmjs.com/package/dependency-graph

**Comment by ljharb** [comment]
It might be worth using whatever jest uses internally.

**Comment by milesj** [comment]
@ljharb Good call out. I'll dig around there.

**Comment by milesj** [comment]
Messing around here: https://github.com/milesj/beemo/pull/34 Doesn't look like it supports everything I need.

**Comment by milesj** [comment]
Implemented my own: https://github.com/beemojs/beemo/pull/41
