### ISSUE TITLE
Prettier driver adds double quotes

### ISSUE THREAD

**Issue by domoritz** [beemojs/beemo#55]
My `configs/prettier.js` file only uses `'` but the generated `prettier.config.js` has `"`. Can the driver be configured to maintain the original quoting or use what is specified in eslint or prettier?

**Comment by milesj** [comment]
@domoritz The `prettier.config.js` is just a JSON dump, it's basically this:

```js
module.exports = JSON.stringify(config);
```

Since these are auto-generated files, there's no other way around it. If you'd like the config to match your guidelines (I personally gitignore the config files), you can run prettier on it yourself.

```
beemo prettier ./src && prettier ./*.config.js --write
```

**Comment by domoritz** [comment]
I see. I personally don't care and I am ignoring ng the files. However, the file causes linting errors later. I just ignored it in my eslint config. Would it make sense to ignore the generated config files by default?

**Comment by milesj** [comment]
@domoritz I usually ignore them, especially if it's a type of config that changes often.

**Comment by domoritz** [comment]
I wish beemo ignored generated files automatically but I don't think it's a big issue so I'll close this.

**Comment by milesj** [comment]
@domoritz What do you mean exactly by beemo ignoring the generated files? 

You can use scaffolding to add ignore patterns to gitignore/npmignore/etc. https://milesj.gitbook.io/beemo/scaffolding

**Comment by domoritz** [comment]
> What do you mean exactly by beemo ignoring the generated files?

In my case, beemo generates both the prettier and eslint config files. Therefore, I think prettier and eslint configs should be ignored by prettier and eslint.

**Comment by milesj** [comment]
@domoritz Not a bad idea, I'll think about it. You can add them to the ignore list manually too.

```
// configs/prettier.js
module.exports = {
  ignore: ['.eslintrc.js', 'prettier.config.js'], // etc
};
```
