### ISSUE TITLE
eslint formatting gets lost

### ISSUE THREAD

**Issue by domoritz** [beemojs/beemo#60]
Is I run eslint, I get errors like

![Screen Shot 2019-08-24 at 9 57 06 AM](https://user-images.githubusercontent.com/589034/63640465-8eb11300-c655-11e9-874d-730e589e03aa.png)

With beemo, I get

![Screen Shot 2019-08-24 at 9 57 31 AM](https://user-images.githubusercontent.com/589034/63640472-9bce0200-c655-11e9-8a26-f814a542d4d8.png)

It would be nice if coloring was preserved.

**Comment by milesj** [comment]
@domoritz Color works on my end. Are you passing the `--color` option?

Also, what version of ESLint, Beemo, etc.

**Comment by domoritz** [comment]
Ahh, I didn't know about the `--color` option. Thanks! Is there a way to enable it y default for eslint (https://milesj.gitbook.io/beemo/driver/eslint)?

I'm using the latest versions but I guess that's not relevant anymore. Again, thank you for your response.

**Comment by milesj** [comment]
@domoritz I use a bootstrap file to always include those options: https://github.com/milesj/build-tool-config/blob/master/packages/config/index.js#L38

More info: https://milesj.gitbook.io/beemo/tool/events
