### ISSUE TITLE
Beemo v1.1.1 build failed

### ISSUE THREAD

**Issue by cdmikechen** [beemojs/beemo#74]
I built project `superset-ui` in https://github.com/apache-superset/superset-ui with master version and it failed. I found that it use `@superset-ui/build-config` and `@superset-ui/build-config` use `beemo`. 
```json
{
    "@beemo/cli": "^1.0.6",
    "@beemo/core": "^1.0.8",
    "@beemo/driver-babel": "^1.0.6",
    "@beemo/driver-eslint": "^1.0.7",
    "@beemo/driver-jest": "^1.0.4",
    "@beemo/driver-prettier": "^1.0.4",
    "@beemo/driver-typescript": "^1.1.5"
}
```
I have open an issue https://github.com/apache-superset/superset-ui/issues/265.
`superset-ui` github link is https://github.com/apache-superset/superset-ui . 
Maybe someone can check what causes the Beemo failure.

**Comment by milesj** [comment]
@cdmikechen Seems like the issue is here: https://github.com/apache-superset/build-config/blob/master/configs/typescript.js#L24 Should be changed to `String(context.workspaceRoot)`.

I probably made an accidental breaking change while adding windows support.
