### ISSUE TITLE
Remove driver-babel as dependency of driver-jest

### ISSUE THREAD

**Issue by matchai** [beemojs/beemo#83]
Hey Miles! 👋

Working on a Jest Beemo config, I have noticed that [driver-babel is depended on by driver-jest](https://github.com/beemojs/beemo/blob/master/packages/driver-jest/src/JestDriver.ts#L12). I see this making sense if the config is going to be using Babel to transpile TypeScript, but in my own use case, I use ts-jest and have no use for a Babel driver or config.

I'm currently using a fork of driver-jest with the dependency removed, and it appears to work perfectly.

What is the purpose of that dependency?
Do you think it would be worthwhile to make Babel optional here?

**Comment by milesj** [comment]
@matchai It's a dependency since Babel is a direct dependency of Jest. It's meant to match how upstream works.

**Comment by matchai** [comment]
Ah, gotcha. 👌
Thanks for the explanation!

Since Babel configuration is optional for the use of Jest itself, it would seem sensible to me that babel configuration be optional, but be used when available.

Jest, by default, will use `babel.config.js` when present in the project root, so there shouldn't need to be anything else to add for it to work that way.

**Comment by milesj** [comment]
Yeah I can look into this. Seems like a breaking change though so would have to wait for v2.

**Comment by milesj** [comment]
Changed in v2.
