### ISSUE TITLE
Webpack driver does not support all events

### ISSUE THREAD

**Issue by hsarb** [beemojs/beemo#84]
I am trying to follow the recommended pattern for listening to events, however, it looks like the webpack driver does not trigger all the events. I am trying to listen to `onCreateConfigFile` but it does not get called and there are no errors reported either.

```js
tool.onRunDriver.listen((context, driver) => {
  ...

  driver.onCreateConfigFile.listen(context => {
     ....
  });

  ...
}, 'webpack');
```

**Comment by milesj** [comment]
@hsarb So webpack by default doesn't create a config file, it references it: https://github.com/beemojs/beemo/blob/master/packages/driver-webpack/src/WebpackDriver.ts#L11 You can try `onReferenceConfigFile`.

**Comment by hsarb** [comment]
I'll give that a shot and report back / close the ticket. Thanks
