### ISSUE TITLE
Allow driver modules to be scoped outside of `@beemo/`

### ISSUE THREAD

**Issue by matchai** [beemojs/beemo#85]
Hey Miles 👋

Folks at @auth0 have started using beemo for internal (and soon open source) projects. We would like to create our own drivers within our own `@auth0/` scope to avoid name collisions, but it looks like only the following drivers will be resolved: `@beemo/driver-X` and `beemo-driver-X`. I think it would be beneficial if folks had the flexibility to use `@X/beemo-driver-Y` for their driver packages.

Looking into how driver resolution works, it looks like module resolution logic is handled by boost. I don't mind getting my hands dirty and making a PR, but it may take me some time to figure out how boost works. Some guidance would be appreciated.

**Comment by milesj** [comment]
@matchai It does support this in the form of `beemo-driver-<name>`.

**Comment by milesj** [comment]
This works in v2 which will land shortly.
