### ISSUE TITLE
Add a rollup driver

### ISSUE THREAD

**Issue by domoritz** [beemojs/beemo#92]
It would be great if you could add a rollup driver that allows me to share rollup configurations across projects.

**Comment by milesj** [comment]
Will land in v2.

**Comment by domoritz** [comment]
I'm looking forward to the v2 release. Let me know when you have an rc and I am happy to take it for a spin.

**Comment by milesj** [comment]
Will do!

**Comment by domoritz** [comment]
The upgrade was pretty smooth except for two typing issues I filed. https://github.com/vega/vega-lite-dev-config/pull/481
